modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
issueTrackerURL="http://github.com/Geforce132/SecurityCraft/issues"
displayURL="http://minecraft.curseforge.com/projects/security-craft"
logoFile="scLogo.png"
credits="Thanks to all of you guys for your support!"
authors="Geforce132, bl4ckscor3"
license="GNU GPL v3.0 https://github.com/Geforce132/SecurityCraft/blob/1.16.x/LICENSE"

[[mods]] #mandatory
modId="securitycraft" #mandatory
version="v1.8.19.3" #mandatory
displayName="SecurityCraft" #mandatory
updateJSONURL="https://www.github.com/Geforce132/SecurityCraft/raw/master/Updates/Forge.json"
description='''
Adds a load of things to keep your house safe with.
If you like this mod, hit the green arrow
in the corner of the forum thread!

Please visit the URL above for help.


Message of the update: Finally! Cameras!
''' #mandatory

[[dependencies.securitycraft]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.securitycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"