modLoader="javafml"
loaderVersion="[45,)"
logoFile="sc_banner.png"
license="MIT https://github.com/Geforce132/SecurityCraft/blob/master/LICENSE"
issueTrackerURL="http://github.com/Geforce132/SecurityCraft/issues"

[[mods]]
	modId="securitycraft"
	version="${file.jarVersion}"
	displayName="SecurityCraft"
	updateJSONURL="https://www.github.com/Geforce132/SecurityCraft/raw/master/Updates/Forge.json"
	description='''Adds a load of things to keep your house safe with and defend yourself from attackers.'''
	displayURL="https://discord.gg/U8DvBAW"
	credits="Thanks to all of you guys for your support!"
	authors="Geforce132, bl4ckscor3, Redstone_Dubstep"

[[dependencies.securitycraft]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.58,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.securitycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"

[modproperties.securitycraft]
    catalogueImageIcon="sc_logo.png"