modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
logoFile="scLogo.png"
issueTrackerURL="http://github.com/Geforce132/SecurityCraft/issues"

[[mods]] #mandatory
	modId="securitycraft" #mandatory
	version="${version}" #mandatory
	displayName="SecurityCraft" #mandatory
	updateJSONURL="https://www.github.com/Geforce132/SecurityCraft/raw/master/Updates/Forge.json"
	description='''Adds a load of things to keep your house safe with and defend yourself from attackers.''' #mandatory
	displayURL="https://discord.gg/U8DvBAW"
	credits="Thanks to all of you guys for your support!"
	authors="Geforce132, bl4ckscor3, Redstone_Dubstep"

[[dependencies.securitycraft]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.securitycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"